### ISSUE TITLE
Support for null safety

### ISSUE THREAD

**Issue by georgeherby** [sudame/dart-rss#12]
I was hoping now that null safety is into beta, you will soon be releasing a null safe build like other packages are doing.

**Comment by georgeherby** [comment]
My assumption is that this is blocked by the http library not having a null safe version yet this is in the master branch but there is no currently a release for it

Issue discussion null safety https://github.com/dart-lang/http/issues/501
PR when it was added https://github.com/dart-lang/http/pull/496

**Comment by sudame** [comment]
Thank you for your issue!

I'm so sorry but now I'm very busy because of my private event.
If possible, please fork this branch and make Pull Request.
I will review and merge it as soon as possible.

Thanks.

**Comment by mzdm** [comment]
Hey @sudame, I have raised a PR. The stable release of null safety is coming really really out soon, please check it when you have time:) Thanks! #14
