### ISSUE TITLE
Incompatible with flutter_localizations because dart-rss depends on Intl 0.17

### ISSUE THREAD

**Issue by gerryhigh** [sudame/dart-rss#31]
If you use a project with anything that uses Intl 0.18 (e.g. built-in flutter localizations) you will get this error:

dart_rss ^3.0.0 which depends on intl ^0.17.0, intl ^0.17.0 is required

please update your package to work with intl 0.18.

I've tested this with 
Flutter version 3.10.5 on channel stable
Engine revision 45f6e00911
Dart version 3.0.5

**Comment by NomadicDeveloper22** [comment]
https://github.com/Flutter-Bounty-Hunters/dart-rss/blob/main/pubspec.yaml

Looks like it already uses 0.18, but the package on pub.dev isn't updated with commit #32 

Having the same issue here and need 0.18

**Comment by matthew-carroll** [comment]
I just released a new version with an upgraded `intl` dependency. I'm going to close this ticket.
