### ISSUE TITLE
XML dependency need to be upgraded

### ISSUE THREAD

**Issue by nobodyyu** [sudame/dart-rss#33]
Because {} depends on dart_rss ^3.0.0 which depends on xml ^5.0.2, xml ^5.0.2 is required.
So, because {} depends on xml ^6.1.0, version solving failed.

**Comment by NomadicDeveloper22** [comment]
Should be fixed with #32 

Awaiting update on pub.dev

**Comment by matthew-carroll** [comment]
v3.0.1 is now available on Pub. Closing this ticket as complete.
