### ISSUE TITLE
Support http^0.12.1 Please

### ISSUE THREAD

**Issue by 276562578** [sudame/dart-rss#7]
Please support http^0.12.1, thanks very much !

**Comment by lironhl** [comment]
The change #5, was already merged, a new version of the package hasn't been published yet...

**Comment by 276562578** [comment]
thanks a lot!

**Comment by flareso** [comment]
http should be used only on example module. we dont need to upgrade we need to delete it

**Comment by sudame** [comment]
Sorry for my slooooooooooooooooow work...
now I publish [new version](https://pub.dev/packages/dart_rss/versions/1.1.0).
