### ISSUE TITLE
Support xml ^4.1.0

### ISSUE THREAD

**Issue by hrubalski** [sudame/dart-rss#9]
Hi, can you add compatibility with xml ^4.1.0?

I have this error with flutter_svg package
flutter_svg >=0.18.0 is incompatible with dart_rss ^1.1.0. Because flutter_svg >=0.18.0 depends on xml ^4.1.0 and dart_rss 1.1.0 depends on xml ^3.0.0, flutter_svg >=0.18.0 is incompatible with dart_rss 1.1.0.

Thank you very much!

**Comment by oberbeck** [comment]
#10
